[WOTCArchipelago.X2Item_ResearchCompleted]

; BASE GAME

; Weapon Techs
+CheckCompleteTechs=(TechName=ModularWeapons)
+CheckCompleteTechs=(TechName=MagnetizedWeapons)
+CheckCompleteTechs=(TechName=GaussWeapons)
+CheckCompleteTechs=(TechName=PlasmaRifle)
+CheckCompleteTechs=(TechName=HeavyPlasma)
+CheckCompleteTechs=(TechName=PlasmaSniper)
+CheckCompleteTechs=(TechName=AlloyCannon)

; Armor Techs
+CheckCompleteTechs=(TechName=HybridMaterials)
+CheckCompleteTechs=(TechName=PlatedArmor)
+CheckCompleteTechs=(TechName=PoweredArmor)

; Elerium Tech
+CheckCompleteTechs=(TechName=Tech_Elerium, CompletionItemName=EleriumCompleted)

; Psionics Tech
+CheckCompleteTechs=(TechName=Psionics)

; Autopsy Techs
+CheckCompleteTechs=(TechName=AlienBiotech)
+CheckCompleteTechs=(TechName=AutopsySectoid)
+CheckCompleteTechs=(TechName=AutopsyViper)
+CheckCompleteTechs=(TechName=AutopsyMuton)
+CheckCompleteTechs=(TechName=AutopsyBerserker)
+CheckCompleteTechs=(TechName=AutopsyArchon)
+CheckCompleteTechs=(TechName=AutopsyGatekeeper)
+CheckCompleteTechs=(TechName=AutopsyAndromedon)
+CheckCompleteTechs=(TechName=AutopsyFaceless)
+CheckCompleteTechs=(TechName=AutopsyChryssalid)
+CheckCompleteTechs=(TechName=AutopsyAdventTrooper)
+CheckCompleteTechs=(TechName=AutopsyAdventStunLancer)
+CheckCompleteTechs=(TechName=AutopsyAdventShieldbearer)
+CheckCompleteTechs=(TechName=AutopsyAdventMEC)
+CheckCompleteTechs=(TechName=AutopsyAdventTurret)
+CheckCompleteTechs=(TechName=AutopsySectopod)

; Golden Path Techs & Shadow Chamber Projects
+CheckCompleteTechs=(TechName=ResistanceCommunications)
+CheckCompleteTechs=(TechName=ResistanceRadio)
+CheckCompleteTechs=(TechName=AutopsyAdventOfficer)
+CheckCompleteTechs=(TechName=AlienEncryption)
+CheckCompleteTechs=(TechName=CodexBrainPt1)
+CheckCompleteTechs=(TechName=CodexBrainPt2)
+CheckCompleteTechs=(TechName=BlacksiteData)
+CheckCompleteTechs=(TechName=ForgeStasisSuit)
+CheckCompleteTechs=(TechName=PsiGate)
+CheckCompleteTechs=(TechName=AutopsyAdventPsiWitch)

; ALIEN HUNTERS

; Experimental Weapons Tech
+CheckCompleteTechs=(TechName=ExperimentalWeapons)

; Autopsy Techs
+CheckCompleteTechs=(TechName=AutopsyViperKing)
+CheckCompleteTechs=(TechName=AutopsyBerserkerQueen)
+CheckCompleteTechs=(TechName=AutopsyArchonKing)

; WAR OF THE CHOSEN

; Autopsy Techs
+CheckCompleteTechs=(TechName=AutopsyAdventPurifier)
+CheckCompleteTechs=(TechName=AutopsyAdventPriest)
+CheckCompleteTechs=(TechName=AutopsyTheLost)
+CheckCompleteTechs=(TechName=AutopsySpectre)

; Chosen Weapon Techs
+CheckCompleteTechs=(TechName=ChosenAssassinWeapons)
+CheckCompleteTechs=(TechName=ChosenHunterWeapons)
+CheckCompleteTechs=(TechName=ChosenWarlockWeapons)


; MOD ENTRIES BEGIN
; MOD ENTRIES END

; ______________________________________________________________________________________________________________________

[WOTCArchipelago.X2EventListener_WOTCArchipelago]

; Default Character Groups
+CheckKillDefaultCharacterGroups=Sectoid
+CheckKillDefaultCharacterGroups=Viper
+CheckKillDefaultCharacterGroups=Muton
+CheckKillDefaultCharacterGroups=Berserker
+CheckKillDefaultCharacterGroups=Archon
+CheckKillDefaultCharacterGroups=Gatekeeper
+CheckKillDefaultCharacterGroups=Andromedon
+CheckKillDefaultCharacterGroups=AndromedonRobot
+CheckKillDefaultCharacterGroups=Faceless
+CheckKillDefaultCharacterGroups=Chryssalid
+CheckKillDefaultCharacterGroups=AdventTrooper
+CheckKillDefaultCharacterGroups=AdventCaptain
+CheckKillDefaultCharacterGroups=Cyberus
+CheckKillDefaultCharacterGroups=AdventPsiWitch
+CheckKillDefaultCharacterGroups=AdventStunLancer
+CheckKillDefaultCharacterGroups=AdventShieldBearer
+CheckKillDefaultCharacterGroups=AdventMEC
+CheckKillDefaultCharacterGroups=AdventTurret
+CheckKillDefaultCharacterGroups=Sectopod
+CheckKillDefaultCharacterGroups=ViperKing
+CheckKillDefaultCharacterGroups=BerserkerQueen
+CheckKillDefaultCharacterGroups=ArchonKing
+CheckKillDefaultCharacterGroups=AdventPurifier
+CheckKillDefaultCharacterGroups=AdventPriest
+CheckKillDefaultCharacterGroups=TheLost
+CheckKillDefaultCharacterGroups=Spectre
+CheckKillDefaultCharacterGroups=ChosenAssassin
+CheckKillDefaultCharacterGroups=ChosenSniper
+CheckKillDefaultCharacterGroups=ChosenWarlock

; Create Custom Character Group
; +CheckKillCustomCharacterGroups=(GroupName=MyCustomGroup, \\
; Members[0]=SomeCharacterTemplateName, \\
; Members[1]=SomeOtherCharacterTemplateName, \\
; ...)

; Ignore Default Group for Character Template
; +CheckKillIgnoreDefaultGroup=SomeCharacterTemplateName

; SPARK Cost Refund
RefundSparkCostSupplies=100
RefundSparkCostAlloys=20
RefundSparkCostElerium=15
RefundSparkCostCores=2


; MOD ENTRIES BEGIN
; MOD ENTRIES END

; ______________________________________________________________________________________________________________________

[WOTCArchipelago.X2Effect_ItemUseCheck]

; Grenades
+CheckUseItems=FragGrenade
+CheckUseItems=AlienGrenade
+CheckUseItems=FlashbangGrenade
+CheckUseItems=SmokeGrenade
+CheckUseItems=SmokeGrenadeMk2
+CheckUseItems=EMPGrenade
+CheckUseItems=EMPGrenadeMk2
+CheckUseItems=ProximityMine
+CheckUseItems=Frostbomb
+CheckUseItems=UltrasonicLure

; Utility
+CheckUseItems=Medikit
+CheckUseItems=NanoMedikit
+CheckUseItems=SKULLJACK
+CheckUseItems=BattleScanner
+CheckUseItems=MimicBeacon
+CheckUseItems=CombatStims
+CheckUseItems=RefractionField

; Heavy Weapons
+CheckUseItems=RocketLauncher

; Ammo
+CheckUseItems=BluescreenRounds

; Experimental Ammo
+CheckUseItemCategories=(CategoryName=ExperimentalAmmo, \\
Members[0]=APRounds, \\
Members[1]=TracerRounds, \\
Members[2]=VenomRounds, \\
Members[3]=IncendiaryRounds, \\
Members[4]=TalonRounds)

; Experimental Grenades
+CheckUseItemCategories=(CategoryName=ExperimentalGrenade, \\
Members[0]=Firebomb, \\
Members[1]=AcidGrenade, \\
Members[2]=GasGrenade, \\
Members[3]=FirebombMk2, \\
Members[4]=AcidGrenadeMk2, \\
Members[5]=GasGrenadeMk2)

; Experimental Bombs
+CheckUseItemCategories=(CategoryName=ExperimentalGrenadeMk2, \\
Members[0]=FirebombMk2, \\
Members[1]=AcidGrenadeMk2, \\
Members[2]=GasGrenadeMk2)

; Experimental Heavy Weapons
+CheckUseItemCategories=(CategoryName=ExperimentalHeavyWeapon, \\
Members[0]=Flamethrower, \\
Members[1]=ShredderGun, \\
Members[2]=FlamethrowerMk2, \\
Members[3]=BlasterLauncher, \\
Members[4]=PlasmaBlaster, \\
Members[5]=ShredstormCannon)

; Experimental Powered Weapons
+CheckUseItemCategories=(CategoryName=ExperimentalPoweredWeapon, \\
Members[0]=FlamethrowerMk2, \\
Members[1]=BlasterLauncher, \\
Members[2]=PlasmaBlaster, \\
Members[3]=ShredstormCannon)

; Upgraded Items
+CheckUseItemCategories=(CategoryName=FragGrenade, Members[0]=AlienGrenade)
+CheckUseItemCategories=(CategoryName=SmokeGrenade, Members[0]=SmokeGrenadeMk2)
+CheckUseItemCategories=(CategoryName=EMPGrenade, Members[0]=EMPGrenadeMk2)
+CheckUseItemCategories=(CategoryName=Medikit, Members[0]=NanoMedikit)

; Gremlin Abilities
+CheckUseItemInInventory=(AbilityName=GremlinHeal, \\
Members[0]=Medikit, \\
Members[1]=NanoMedikit)
+CheckUseItemInInventory=(AbilityName=GremlinStabilize, \\
Members[0]=Medikit, \\
Members[1]=NanoMedikit)

; Reaction Shot Abilities
+CheckUseItemExcludeAbilities=Overwatch
+CheckUseItemExcludeAbilities=SniperRifleOverwatch
+CheckUseItemIncludeAbilities=OverwatchShot
+CheckUseItemExcludeAbilities=PistolOverwatch
+CheckUseItemIncludeAbilities=PistolOverwatchShot
+CheckUseItemExcludeAbilities=LongWatch
+CheckUseItemIncludeAbilities=LongWatchShot
+CheckUseItemExcludeAbilities=KillZone
+CheckUseItemIncludeAbilities=KillZoneShot
+CheckUseItemExcludeAbilities=Suppression
+CheckUseItemIncludeAbilities=SuppressionShot


; MOD ENTRIES BEGIN
; MOD ENTRIES END

; ______________________________________________________________________________________________________________________

[WOTCArchipelago.WOTCArchipelago_Ranksanity]

; Ranksanity Data
+RanksanityData=(ID=DefaultRanger, SoldierClass=Ranger, \\
Ranks[0]=2, Ranks[1]=3, Ranks[2]=4, Ranks[3]=5, Ranks[4]=6, Ranks[5]=7)
+RanksanityData=(ID=DefaultGrenadier, SoldierClass=Grenadier, \\
Ranks[0]=2, Ranks[1]=3, Ranks[2]=4, Ranks[3]=5, Ranks[4]=6, Ranks[5]=7)
+RanksanityData=(ID=DefaultSpecialist, SoldierClass=Specialist, \\
Ranks[0]=2, Ranks[1]=3, Ranks[2]=4, Ranks[3]=5, Ranks[4]=6, Ranks[5]=7)
+RanksanityData=(ID=DefaultSharpshooter, SoldierClass=Sharpshooter, \\
Ranks[0]=2, Ranks[1]=3, Ranks[2]=4, Ranks[3]=5, Ranks[4]=6, Ranks[5]=7)
+RanksanityData=(ID=DefaultSkirmisher, SoldierClass=Skirmisher, \\
Ranks[0]=2, Ranks[1]=3, Ranks[2]=4, Ranks[3]=5, Ranks[4]=6, Ranks[5]=7)
+RanksanityData=(ID=DefaultReaper, SoldierClass=Reaper, \\
Ranks[0]=2, Ranks[1]=3, Ranks[2]=4, Ranks[3]=5, Ranks[4]=6, Ranks[5]=7)
+RanksanityData=(ID=DefaultTemplar, SoldierClass=Templar, \\
Ranks[0]=2, Ranks[1]=3, Ranks[2]=4, Ranks[3]=5, Ranks[4]=6, Ranks[5]=7)
+RanksanityData=(ID=DefaultSpark, SoldierClass=Spark, \\
Ranks[0]=2, Ranks[1]=3, Ranks[2]=4, Ranks[3]=5, Ranks[4]=6, Ranks[5]=7)

; Toggleable Soldier Classes
+FactionSoldierClasses=Skirmisher
+FactionSoldierClasses=Reaper
+FactionSoldierClasses=Templar
+SLGSoldierClasses=Spark

; Ranksanity Client Toggles
bEnableRanksanity=False
bDisableFactionSoldierClasses=False
bDisableSLGSoldierClasses=False

; Disable Ranksanity Data Entries
; +DisabledDataEntries=SomeRanksanityDataEntryID


; MOD ENTRIES BEGIN
; MOD ENTRIES END

; ______________________________________________________________________________________________________________________

[WOTCArchipelago.X2StrategyElement_OverrideMissionSources]

; Skipped Supply Raid Rewards
SupplyRaidSkipMaxSupplies=200
SupplyRaidSkipMaxAlloys=80
SupplyRaidSkipMaxElerium=40
SupplyRaidSkipMaxCores=3

; ______________________________________________________________________________________________________________________

[WOTCArchipelago.WOTCArchipelago_Version]
ModVersion=0.10.4
MinimumClientVersion=0.10.0
ClientVersion=
MinimumModVersion=
WorldVersion=

[WOTCArchipelago.WOTCArchipelago_TcpLink]
ProxyPort=0

[WOTCArchipelago.WOTCArchipelago_UISL_ShellSplash]
bAllowInvalidLaunch=False

[WOTCArchipelago.WOTCArchipelago_APClient]
bRequirePsiGate=False
bRequireStasisSuit=False
bRequireAvatarCorpse=False

[WOTCArchipelago.X2DLCInfo_WOTCArchipelago]
DLCIdentifier=WOTCArchipelago

bRemoveScienceRequirements=True
bRemoveEngineeringRequirements=True
bRemoveCorpseCosts=False

; ______________________________________________________________________________________________________________________

[WOTCArchipelago.WOTCArchipelago_Defaults]

; Unique AP generation ID set by the client
DEF_AP_GEN_ID=

; Enable debug logging to /Documents/My Games/XCOM2 War of the Chosen/XComGame/Logs/Launch.log
DEF_DEBUG_LOGGING=True

; Hint research projects
DEF_HINT_TECH_LOC_PART=False
DEF_HINT_TECH_LOC_FULL=False

; Skip certain time-consuming missions
DEF_SKIP_SUPPLY_RAIDS=True
DEF_SKIP_COUNCIL_MISSIONS=True
DEF_SKIP_FACTION_MISSIONS=True

; Disable certain time-consuming covert op risks
DEF_DISABLE_AMBUSH_RISK=True
DEF_DISABLE_CAPTURE_RISK=True

; Skipped supply raid rewards
DEF_SKIP_RAID_REWARD_MULT_BASE=0.5
DEF_SKIP_RAID_REWARD_MULT_ERR=0.15

; Increase XP/corpse gain
DEF_EXTRA_XP_MULT=0.35
DEF_EXTRA_CORPSES=1

; Improve access to soldiers
DEF_INSTANT_ROOKIE_TRAINING=True
DEF_INSTANT_SPARK_BUILDING=True
DEF_REFUND_SPARK_COST=True
DEF_REPLACE_FACTION_HERO=True

; Disable day 1 traps
DEF_NO_STARTING_TRAPS=False

; MCM version
DEF_VERSION=1
